services:
  frontend:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_FRONTEND}:${TAG:-latest}
    restart: always
    env_file:
      - .env
    networks:
      - default
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://api.${DOMAIN}
        - NODE_ENV=production

  backend:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_BACKEND}:${TAG:-latest}
    restart: always
    env_file:
      - .env
    networks:
      - default
    build:
      context: ./backend
