apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-backend-config
  namespace: fastapi-backend
data:
  IMAGE_BACKEND_TAG: "latest"

---

apiVersion: v1
kind: Secret
metadata:
  name: fastapi-backend-secrets
  namespace: fastapi-backend
type: Opaque
stringData:
  secret-key: "AahZZSyMmAF3bkq4ct5qbxE8qWQpEK8bs3RbesSVL44"
  first-superuser: "tqhung0105@gmail.com"
  first-superuser-password: "hungqt"
  postgres-user: "fastapi"
  postgres-password: "hungqt"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend-deployment
  labels:
    app: fastapi-backend-deployment
  namespace: fastapi-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fastapi-backend-deployment
      namespace: fastapi-backend
    spec:
      containers:
        - name: fastapi-backend
          image: 'tqhung0105/fastapi-backend:latest'
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: DOMAIN
              value: "fastapi.local"
            - name: FRONTEND_HOST
              value: "https://fastapi.local"
            - name: BACKEND_CORS_ORIGINS
              value: "https://fastapi.local,https://dashboard.fastapi.local"
            - name: PROJECT_NAME
              value: "Full Stack FastAPI Project"
            - name: SECRET_KEY
              value: AahZZSyMmAF3bkq4ct5qbxE8qWQpEK8bs3RbesSVL44
            - name: FIRST_SUPERUSER
              value: fastapi
            - name: FIRST_SUPERUSER_PASSWORD
              value: fastapi
            - name: POSTGRES_SERVER
              value: "192.168.64.192"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "fastapi"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fastapi-backend-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastapi-backend-secrets
                  key: postgres-password
            - name: EMAILS_FROM_EMAIL
              value: "info@example.com"

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-clusterip
  namespace: fastapi-backend
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: fastapi-backend-deployment
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-backend-ingress
  namespace: fastapi-backend
spec:
  ingressClassName: nginx
  rules:
    - host: api.fastapi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-backend-clusterip
                port:
                  number: 8000

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-backend-hpa
  namespace: fastapi-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-backend-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50